### ISSUE TITLE
How to run tests

### ISSUE THREAD

**Issue by fendor** [bubba/lsp-test#29] opened 2019-02-20 15:01 UTC
I am trying to execute the tests via `cabal new-test` as well as `stack test`. 
On the former, the tests hang indefinitely long, on the latter 30/31 tests fail.

I am thinking I may be doing something wrong, what is necessary to run the tests?

**Comment by bubba** [comment] 2019-02-21 18:39
What operating system are you on? At the moment I don’t think it works on windows (this isn’t intentional!). There’s a specific version of hie that needs to be installed into your path as well as a javascript language server, check out .travis.yml, it has the commands used to install them

**Comment by fendor** [comment] 2019-02-25 16:52
Since the tests are not unit tests, it might be related to problems regarding hie on windows. 

Is the exact hie version important? or is it ok to use `hie` version `0.6.0.0`?

**Comment by bubba** [comment] 2019-02-25 21:47
For the same as CircleCI, use `890ca3f2f3bd3bfe74e1f38a426b383a847763bb`, but ideally I would try to test it with the latest HIE on master. If you're on Windows then this is probably a duplicate of #28. I'm not exactly sure why it hangs, but if you have any ideas or clues as to why this is happening please do share

**Closed** 2019-03-31 05:09 UTC
